version: '3.1'

services:
  padel_backend_prod:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: padel_backend_prod
    restart: always
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 8080:8080
    env_file:
      - .env.prod

  padel_frontend_prod:
    build:
      context: frontend
      dockerfile: Dockerfile.prod
    container_name: padel_frontend_prod
    depends_on:
      - padel_backend_prod
    restart: always
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 80:80
    env_file:
      - .env.prod

  padel_db_prod:
    image: postgres
    container_name: padel_db_prod
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env.prod
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  padel_bot_prod:
    build: backend
    container_name: padel_bot_prod
    command: python3 start_bot.py
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - padel_frontend_prod
    env_file:
      - .env.prod
